/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.revature;

import com.revature.models.*;
import com.revature.services.*;
import com.revature.dao.*;

import com.revature.exceptions.UsernameOrPasswordIncorrectException;

import java.util.Scanner;
import java.util.List;
import java.util.Iterator;

public class Driver {

        // we can implement postgres instead of UserDaoMock
        private static IUserDao uDao = new UserDaoMock();
        private static UserService uServ = new UserService(uDao);




    public static void main(String[] args) {

        Scanner scan = new Scanner(System.in);
        boolean isDone = false;
        User loggedIn = null;

        MockUserDB.getInstance().populateUsers();

        while(!isDone) {

            // use if else to see if user exist in the db
            if (loggedIn == null) {
                System.out.println("You are not logged in");
                System.out.println("Select 1 for register and 2 for Login");

                String userInput = scan.nextLine();

                if (userInput.equalsIgnoreCase("1")) {
                    System.out.println("Enter your first name please");
                    String first = scan.nextLine();

                    System.out.println("Enter your last name please");
                    String last = scan.nextLine();

                    System.out.println("Enter your username please");
                    String username = scan.nextLine();

                    System.out.println("Please enter if you are user or manager");
                    String userType = scan.nextLine();

                    System.out.println("Enter your email please");
                    String email = scan.nextLine();

                    System.out.println("Enter your password please");
                    String password = scan.nextLine();

                    // user information coming from postman
                    // pass user info to UserService
                    // talk to DAO and save onto DB
                    uServ.registerUser(first, last, username, userType, email, password);

                } else {
                    // this is coming from UserService loginUser method
                    System.out.println("Enter your username");
                    String username = scan.nextLine();

                    System.out.println("Enter your password please");
                    String password = scan.nextLine();

                    try {
                        loggedIn = uServ.loginUser(username, password);
                        System.out.println(loggedIn);


                    } catch (UsernameOrPasswordIncorrectException e) {
                        e.printStackTrace();
                    }
                }
            } else {
                System.out.println("Hey!!! you are logged in now");

                // once they are logged in user can deposit, withdraw and transfer

                System.out.println("Welcome to Revature Bank");
                System.out.println("Chose");
                System.out.println("1 for deposit");
                System.out.println("2 for withdraw");
                System.out.println("3 for transfer");
                System.out.println("4 to check your balance");
                int input = scan.nextInt();
                scan.nextLine();
                switch (input) {
                    case 1:
                        break;

                    case 2:
                        break;

                    case 3:
                        // showing an iterator
                        List<User> uList = uServ.getTopUsers();
                        Iterator<User> uIter = uList.iterator();
                        System.out.println("username\t\t\t\tFollowers");

                        while (uIter.hasNext()) {
                            User u = uIter.next();
                            System.out.println(u.getUsername() + "\t\t\t\t" + u.getFollowers().size());
                        }
                        break;
                }
                isDone = true;
            }


        }

    }
}
