/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.revature;

import com.revature.dao.UserDaoMock;
import com.revature.exceptions.UsernameOrPasswordIncorrectException;
import com.revature.models.*;
import com.revature.services.UserService;
import com.revature.dao.*;
import com.revature.exceptions.UsernameOrPasswordIncorrectException;

import java.util.Scanner;

public class Driver {

        // we can implement postgres instead of UserDaoMock
        private static IUserDao uDao = new UserDaoMock();
        private static UserService uServ = new UserService(uDao);


    public static void main(String[] args) {

        Scanner scan = new Scanner(System.in);
        boolean isDone = false;
        User loggedIn = null;

        while(!isDone) {

            System.out.println("Welcome to Revature Bank");

            // use if else to see if user exist in the db
            if (loggedIn == null) {
                System.out.println("You are not logged in");
                System.out.println("Select 1 for register and 2 for Login");

                String userInput = scan.nextLine();

                if (userInput.equalsIgnoreCase("1")) {
                    System.out.println("Enter your first name please");
                    String first = scan.nextLine();

                    System.out.println("Enter your last name please");
                    String last = scan.nextLine();

                    System.out.println("Enter your username please");
                    String username = scan.nextLine();

                    System.out.println("Please enter if you are user or manager");
                    String userType = scan.nextLine();

                    System.out.println("Enter your email please");
                    String email = scan.nextLine();

                    System.out.println("Enter your password please");
                    String password = scan.nextLine();

                    // user information coming from postman
                    // pass user info to UserService
                    // talk to DAO and save onto DB
                    uServ.registerUser(first, last, username, userType, email, password);

                } else {
                    // this is coming from UserService loginUser method
                    System.out.println("Enter your username");
                    String username = scan.nextLine();

                    System.out.println("Enter your password please");
                    String password = scan.nextLine();

                    try {
                        loggedIn = uServ.loginUser(username, password);
                        System.out.println(loggedIn);
                    } catch (UsernameOrPasswordIncorrectException e) {
                        e.printStackTrace();
                    }
                }
            } else {
                System.out.println("Hey!!! you are logged in now");
                isDone = true;
            }


        }

    }
}
